name: C/C++ CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]
      types: [opened]
  workflow_dispatch:
   
jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3

      # Packages for coveralls
      - name: install packages
        run: |
          pip install --user cpp-coveralls
          sudo apt-get install -y -qq lcov
      
      # Install Dependencies
      - name: install dependencies
        run: run: sudo apt-get install -y libeigen3-dev; sudo apt-get install libopencv-dev;sudo apt-get install libopencv-contrib-dev
      
      # Start build
      - name: build
        run: |
          export CXX=$COMPILER;
          cmake -D COVERAGE=ON -D CMAKE_BUILD_TYPE=Debug -B ${{github.workspace}}/build 
      - name: make
        working-directory: ${{github.workspace}}/build
        run: |
          make
          make code_coverage
          
     # Upload coverage result to Coverage.io 
      - name: Upload result to Coveralls.io
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{github.workspace}}/build/coverage.info.cleaned

